// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	"github.com/aql-lang/aql/eng"
	sdk "github.com/voxgig-sdk/argentinadatos-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.ArgentinadatosSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.ArgentinadatosSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.ArgentinadatosSDK, name string) (sdk.ArgentinadatosEntity, error) {
	switch strings.ToLower(name) {
	case "acta":
		return client.Acta(nil), nil
	case "bonos_cer":
		return client.BonosCer(nil), nil
	case "cotizacion":
		return client.Cotizacion(nil), nil
	case "criptopeso":
		return client.Criptopeso(nil), nil
	case "cuenta_remunerada_usd":
		return client.CuentaRemuneradaUsd(nil), nil
	case "diputado":
		return client.Diputado(nil), nil
	case "entidad_rendimiento":
		return client.EntidadRendimiento(nil), nil
	case "estado":
		return client.Estado(nil), nil
	case "evento_presidencial":
		return client.EventoPresidencial(nil), nil
	case "feriado":
		return client.Feriado(nil), nil
	case "finanza":
		return client.Finanza(nil), nil
	case "fondo_comun_inversion":
		return client.FondoComunInversion(nil), nil
	case "fondo_comun_inversion_otro":
		return client.FondoComunInversionOtro(nil), nil
	case "fondo_comun_inversion_variable":
		return client.FondoComunInversionVariable(nil), nil
	case "hipotecario_uva_tna":
		return client.HipotecarioUvaTna(nil), nil
	case "indice_inflacion":
		return client.IndiceInflacion(nil), nil
	case "indice_uva":
		return client.IndiceUva(nil), nil
	case "letra":
		return client.Letra(nil), nil
	case "presidente":
		return client.Presidente(nil), nil
	case "proveedor_plazo_fijo_precancelable":
		return client.ProveedorPlazoFijoPrecancelable(nil), nil
	case "proveedor_plazo_fijo_uva_pago_periodico":
		return client.ProveedorPlazoFijoUvaPagoPeriodico(nil), nil
	case "rem":
		return client.Rem(nil), nil
	case "rem_expectativa":
		return client.RemExpectativa(nil), nil
	case "rendimiento":
		return client.Rendimiento(nil), nil
	case "riesgo_pai":
		return client.RiesgoPai(nil), nil
	case "senador":
		return client.Senador(nil), nil
	case "tasa_intere":
		return client.TasaIntere(nil), nil
	case "tasa_plazo_fijo":
		return client.TasaPlazoFijo(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
