// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/argentinadatos-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"acta | bonos_cer | cotizacion | criptopeso | cuenta_remunerada_usd | diputado | entidad_rendimiento | estado | evento_presidencial | feriado | finanza | fondo_comun_inversion | fondo_comun_inversion_otro | fondo_comun_inversion_variable | hipotecario_uva_tna | indice_inflacion | indice_uva | letra | presidente | proveedor_plazo_fijo_precancelable | proveedor_plazo_fijo_uva_pago_periodico | rem | rem_expectativa | rendimiento | riesgo_pai | senador | tasa_intere | tasa_plazo_fijo"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.ArgentinadatosSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "argentinadatos_list",
		Description: "List records from Argentinadatos. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "argentinadatos_load",
		Description: "Load a single record from Argentinadatos. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.ArgentinadatosSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.ArgentinadatosSDK, name string) (sdk.ArgentinadatosEntity, error) {
	switch strings.ToLower(name) {
	case "acta":
		return client.Acta(nil), nil
	case "bonos_cer":
		return client.BonosCer(nil), nil
	case "cotizacion":
		return client.Cotizacion(nil), nil
	case "criptopeso":
		return client.Criptopeso(nil), nil
	case "cuenta_remunerada_usd":
		return client.CuentaRemuneradaUsd(nil), nil
	case "diputado":
		return client.Diputado(nil), nil
	case "entidad_rendimiento":
		return client.EntidadRendimiento(nil), nil
	case "estado":
		return client.Estado(nil), nil
	case "evento_presidencial":
		return client.EventoPresidencial(nil), nil
	case "feriado":
		return client.Feriado(nil), nil
	case "finanza":
		return client.Finanza(nil), nil
	case "fondo_comun_inversion":
		return client.FondoComunInversion(nil), nil
	case "fondo_comun_inversion_otro":
		return client.FondoComunInversionOtro(nil), nil
	case "fondo_comun_inversion_variable":
		return client.FondoComunInversionVariable(nil), nil
	case "hipotecario_uva_tna":
		return client.HipotecarioUvaTna(nil), nil
	case "indice_inflacion":
		return client.IndiceInflacion(nil), nil
	case "indice_uva":
		return client.IndiceUva(nil), nil
	case "letra":
		return client.Letra(nil), nil
	case "presidente":
		return client.Presidente(nil), nil
	case "proveedor_plazo_fijo_precancelable":
		return client.ProveedorPlazoFijoPrecancelable(nil), nil
	case "proveedor_plazo_fijo_uva_pago_periodico":
		return client.ProveedorPlazoFijoUvaPagoPeriodico(nil), nil
	case "rem":
		return client.Rem(nil), nil
	case "rem_expectativa":
		return client.RemExpectativa(nil), nil
	case "rendimiento":
		return client.Rendimiento(nil), nil
	case "riesgo_pai":
		return client.RiesgoPai(nil), nil
	case "senador":
		return client.Senador(nil), nil
	case "tasa_intere":
		return client.TasaIntere(nil), nil
	case "tasa_plazo_fijo":
		return client.TasaPlazoFijo(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
